# Generated by Django 3.1.5 on 2021-02-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticfile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticFileExample',
        ),
    ]
